export default {
  monacoThemes: ['vs-dark', 'light'],
  languages: {
    'C++': 'cpp',
    Javascript: 'javascript',
    Java: 'java',
    C: 'c',
    Python: 'python',
    Typescript: 'typescript',
    Go: 'go',
    'C#': 'csharp',
    Assembly: 'assembly',
    Ats: 'ats',
    Bash: 'bash',
    Clojure: 'clojure',
    Cobol: 'cobol',
    Coffeescript: 'coffeescript',
    Crystal: 'crystal',
    D: 'd',
    Elixir: 'elixir',
    Elm: 'elm',
    Erlang: 'erlang',
    Fsharp: 'fsharp',
    Groovy: 'groovy',
    Hare: 'hare',
    Haskell: 'haskell',
    Idris: 'idris',
    Julia: 'javascript',
    Kotlin: 'kotlin',
    Lua: 'lua',
    Mercury: 'mercury',
    Nim: 'nim',
    Nix: 'nix',
    Ocaml: 'ocaml',
    Perl: 'perl',
    Php: 'php',
    Raku: 'raku',
    Ruby: 'ruby',
    Rust: 'rust',
    Sac: 'sac',
    Scala: 'scala',
    Swift: 'swift',
    Zig: 'zig',
  },
  templates: {
    python: `a = 10\nprint(a)`,
    javascript: `const a = 10;\nconsole.log(a);`,
    typescript: `let a: number;\na = 10;\nconsole.log(a);`,
    c: `#include <stdio.h>\n\nint main() {\n\tint a = 10;\n\tprintf("%d", a);\n\treturn 0;\n}\n`,
    cpp: `#include<iostream>\n\nusing namespace std;\n\nint main() {\n\tint a = 10;\n\tcout << a;\n\treturn 0;\n}\n`,
    go: `package main\n\nimport (\n\t"fmt"\n)\n\nfunc main() {\n\tvar a = 10;\n\tfmt.Println(a)\n} `,
    java: `class Main {\n\tpublic static void main(String[] args) {\n\t\tint a = 10;\n\t\tSystem.out.println(a);\n\t}\n} `,
    csharp: `using System;\nclass MainClass {\n\tstatic void Main(){\n\t\tint a = 10;\n\t\tConsole.WriteLine(a);\n\t}\n}`,
  },
};
