export default {
  "CodeForces":"codeforces",
"CodeForces::Gym":"codeforces_gym",
"TopCoder":"top_coder",
"AtCoder":"at_coder",
"CS Academy":"cs_academy",
"CodeChef":"code_chef",
"HackerRank": "hacker_rank",
"HackerEarth" : "hacker_earth",
"Kick Start":"kick_start",
"LeetCode":"leet_code",
"Toph":"toph",
"codeforces" : "CodeForces",
"codeforces_gym" : "CodeForces::Gym",
"top_coder" :"TopCoder",
"at_coder" : "AtCoder",
"cs_academy" : "CS Academy",
"code_chef" : "CodeChef",
"hacker_rank" : "HackerRank",
"hacker_earth" : "HackerEarth",
"kick_start" : "Kick Start",
"leet_code" : "LeetCode",
"toph" : "Toph"

}